objects = \
	./jukebox/Sound/Sound.o ./jukebox/Sound/SoundImpl.o ./jukebox/Sound/Factory.o ./jukebox/FileFormats/MIDIFactory.o \
	./jukebox/Sound/FileWriterSoundImpl.o \
	./jukebox/FileFormats/SoundFile.o ./jukebox/FileFormats/SoundFileImpl.o \
	./jukebox/FileFormats/WaveFileImpl.o ./jukebox/FileFormats/VorbisFileImpl.o \
	./jukebox/FileFormats/MP3FileImpl.o ./jukebox/FileFormats/MIDIFileImpl.o \
	./jukebox/FileFormats/FLACFileImpl.o \
	./jukebox/Mixer/Mixer.o \
	./jukebox/Sound/Decorators/FadeOnStopSoundImpl.o \
	./jukebox/Decoders/Decorators/DistortionImpl.o \
	./jukebox/Decoders/Decorators/FadeOnStopImpl.o ./jukebox/Decoders/Decorators/FadeImpl.o \
	./jukebox/Decoders/Decorators/ReverbImpl.o ./jukebox/Decoders/Decorators/SampleResolutionImpl.o \
	./jukebox/Decoders/Decoder.o ./jukebox/Decoders/DecoderImpl.o ./jukebox/Decoders/WaveDecoderImpl.o  \
	./jukebox/Decoders/VorbisDecoderImpl.o \
	./jukebox/Decoders/MP3DecoderImpl.o ./jukebox/Decoders/MIDIDecoderImpl.o ./jukebox/Decoders/FLACDecoderImpl.o \
	./jukebox/Sound/SoundBuilder.o ./jukebox/Decoders/fluidsynth/fs.o

SRCS = \
	./jukebox/Sound/Sound.cpp ./jukebox/Sound/SoundImpl.cpp ./jukebox/Sound/Factory.cpp ./jukebox/FileFormats/MIDIFactory.cpp \
	./jukebox/Sound/FileWriterSoundImpl.cpp \
	./jukebox/FileFormats/SoundFile.cpp ./jukebox/FileFormats/SoundFileImpl.cpp \
	./jukebox/FileFormats/WaveFileImpl.cpp ./jukebox/FileFormats/VorbisFileImpl.cpp \
	./jukebox/FileFormats/MP3FileImpl.cpp ./jukebox/FileFormats/MIDIFileImpl.cpp ./jukebox/FileFormats/FLACFileImpl.cpp \
	./jukebox/Mixer/Mixer.cpp \
	./jukebox/Decoders/Decorators/DistortionImpl.cpp \
	./jukebox/Decoders/Decorators/FadeOnStopImpl.cpp ./jukebox/Decoders/Decorators/FadeImpl.cpp \
	./jukebox/Decoders/Decorators/ReverbImpl.cpp ./jukebox/Decoders/Decorators/SampleResolutionImpl.cpp \
	./jukebox/Decoders/Decoder.cpp ./jukebox/Decoders/DecoderImpl.cpp ./jukebox/Decoders/WaveDecoderImpl.cpp \
	./jukebox/Decoders/VorbisDecoderImpl.cpp \
	./jukebox/Decoders/MP3DecoderImpl.cpp ./jukebox/Decoders/MIDIDecoderImpl.cpp ./jukebox/Decoders/FLACDecoderImpl.cpp \
	./jukebox_test/demo/test.cpp ./jukebox_test/demo/play.cpp ./jukebox_test/demo/loop.cpp \
	./jukebox/Sound/SoundBuilder.cpp ./jukebox/Decoders/fluidsynth/fs.c

DEPDIR := .d
$(shell mkdir -p $(DEPDIR) >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Sound >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Decoders/Decorators >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Decoders/fluidsynth >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Sound/Decorators >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Decoders >/dev/null)      
$(shell mkdir -p $(DEPDIR)/jukebox/FileFormats >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox/Mixer >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox_test >/dev/null)
$(shell mkdir -p $(DEPDIR)/jukebox_test/demo >/dev/null)
DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td

COMPILE.c = $(CC) $(DEPFLAGS) $(CFLAGS) $(TARGET_ARCH) -c
COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
POSTCOMPILE = @mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d && touch $@

%.o	:	%.c
%.o	:	%.c $(DEPDIR)/%.d
	$(COMPILE.c) $(OUTPUT_OPTION) $<
	$(POSTCOMPILE)

%.o	:	%.cc
%.o	:	%.cc $(DEPDIR)/%.d
	$(COMPILE.cc) $(OUTPUT_OPTION) $<
	$(POSTCOMPILE)

%.o	:	%.cxx
%.o	:	%.cxx $(DEPDIR)/%.d
	$(COMPILE.cc) $(OUTPUT_OPTION) $<
	$(POSTCOMPILE)

$(DEPDIR)/%.d: ;
.PRECIOUS: $(DEPDIR)/%.d

include $(wildcard $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS))))
	