objects = \
	./jukebox/Sound/Sound.o ./jukebox/Sound/SoundImpl.o ./jukebox/Sound/Factory.o \
	./jukebox/FileFormats/SoundFile.o ./jukebox/FileFormats/SoundFileImpl.o \
	./jukebox/FileFormats/WaveFileImpl.o ./jukebox/FileFormats/VorbisFileImpl.o \
	./jukebox/FileFormats/MP3FileImpl.o ./jukebox/FileFormats/MIDIFileImpl.o \
	./jukebox/FileFormats/FLACFileImpl.o \
	./jukebox/Mixer/Mixer.o \
	./jukebox/Sound/Decorators/FadeOnStopSoundImpl.o \
	./jukebox/Decoders/Decorators/FadeOnStopImpl.o ./jukebox/Decoders/Decorators/FadeImpl.o \
	./jukebox/Decoders/Decorators/ReverbImpl.o \
	./jukebox/Decoders/Decoder.o ./jukebox/Decoders/DecoderImpl.o ./jukebox/Decoders/WavePCMDecoderImpl.o  \
	./jukebox/Decoders/WaveFloatDecoderImpl.o ./jukebox/Decoders/VorbisDecoderImpl.o \
	./jukebox/Decoders/MP3DecoderImpl.o ./jukebox/Decoders/MIDIDecoderImpl.o ./jukebox/Decoders/FLACDecoderImpl.o

SRCS = \
	./jukebox/Sound/Sound.cpp ./jukebox/Sound/SoundImpl.cpp ./jukebox/Sound/Factory.cpp \
	./jukebox/FileFormats/SoundFile.cpp ./jukebox/FileFormats/SoundFileImpl.cpp \
	./jukebox/FileFormats/WaveFileImpl.cpp ./jukebox/FileFormats/VorbisFileImpl.cpp \
	./jukebox/FileFormats/MP3FileImpl.cpp ./jukebox/FileFormats/MIDIFileImpl.cpp ./jukebox/FileFormats/FLACFileImpl.cpp \
	./jukebox/Mixer/Mixer.cpp \
	./jukebox/Decoders/Decorators/FadeOnStopImpl.cpp ./jukebox/Decoders/Decorators/FadeImpl.cpp \
	./jukebox/Decoders/Decorators/ReverbImpl.cpp \
	./jukebox/Decoders/Decoder.cpp ./jukebox/Decoders/DecoderImpl.cpp ./jukebox/Decoders/WavePCMDecoderImpl.cpp \
	./jukebox/Decoders/WaveFloatDecoderImpl.cpp ./jukebox/Decoders/VorbisDecoderImpl.cpp \
	./jukebox/Decoders/MP3DecoderImpl.cpp ./jukebox/Decoders/MIDIDecoderImpl.cpp ./jukebox/Decoders/FLACDecoderImpl.cpp \
	./jukebox_test/demo/test.cpp ./jukebox_test/demo/play.cpp ./jukebox_test/demo/loop.cpp
