package(default_visibility = ["//jukebox:__subpackages__"])

cc_library(
	name = "Decorators",
	srcs = glob(["*.cpp"]),
	hdrs = glob(["*.h"]),
	deps = [
		"//jukebox/FileFormats:sound_file_impl",
	],
)
