package(default_visibility = ["//visibility:public"])

cc_library(
	name = "mixer",
	srcs = ["Mixer.cpp"],
	hdrs = ["Mixer.h"],
	deps = [":mixer_impl"],
)

cc_library(
	name = "mixer_impl",
	srcs = ["MixerImpl.h"],
)
